"""seasonal event

Revision ID: 0b336e849639
Revises: b14c99fb4d1f
Create Date: 2024-12-28 00:40:53.135805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b336e849639'
down_revision: Union[str, None] = 'b14c99fb4d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasonal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_seasonal_event_name')
    )
    op.add_column('product', sa.Column('seasonal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'seasonal_event', ['seasonal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'seasonal_id')
    op.drop_table('seasonal_event')
    # ### end Alembic commands ###
