"""category_unique

Revision ID: 3c654d9dc4fe
Revises: 777d8d172704
Create Date: 2024-12-27 20:20:04.239933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c654d9dc4fe'
down_revision: Union[str, None] = '777d8d172704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_level', 'category', ['name', 'level'])
    op.create_unique_constraint('uq_category_slug', 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_slug', 'category', type_='unique')
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    # ### end Alembic commands ###
