"""category_nullable

Revision ID: 602189efb662
Revises: d8d5eba3bc45
Create Date: 2024-12-27 19:57:44.370274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602189efb662'
down_revision: Union[str, None] = 'd8d5eba3bc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('category', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('category', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
