"""product image table

Revision ID: b14c99fb4d1f
Revises: 8bbf47d76013
Create Date: 2024-12-28 00:30:53.692640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14c99fb4d1f'
down_revision: Union[str, None] = '8bbf47d76013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternative_text', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order', 'product_line_id', name='uq_product_image_order_product_line_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    # ### end Alembic commands ###
