"""category_columns

Revision ID: d8d5eba3bc45
Revises: 3dc822268cba
Create Date: 2024-12-27 19:46:19.638540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d5eba3bc45'
down_revision: Union[str, None] = '3dc822268cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=120), nullable=True))
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'parent_id')
    op.drop_column('category', 'level')
    op.drop_column('category', 'is_active')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
