name: feathers
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
   sdk: '>=3.0.2 <4.0.0'

dependencies:
   flutter:
      sdk: flutter
   http: ^1.0.0
   intl: ^0.18.1
   collection: ^1.17.1

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^2.0.0
   flutter_launcher_icons: '^0.13.1'

flutter:
   uses-material-design: true
   assets:
      - assets/

flutter_launcher_icons:
   image_path: assets/logo.jpg
   ios: true
   remove_alpha_ios: true
   android: false
