networks:
   dev-network:
      driver: bridge

services:
   dev-db:
      image: postgres:16.1-alpine3.19
      restart: always
      env_file:
         - ./.env
      ports:
         - '5433:5432'
      volumes:
         - ./scripts:/docker-entrypoint-initdb.d
      networks:
         - dev-network

name: fastapi-development
